obstacle_range: 1.0
raytrace_range: 0.2
footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
#robot_radius: ir_of_robot
inflation_radius: 1.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: velodyne, data_type: LaserScan, topic: scan, marking: true, clearing: true}

